[project]
id = "transformr-prod"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "exp://localhost:8081"
additional_redirect_urls = ["transformr://", "exp://localhost:8081"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = true
client_id = ""
secret = ""

[auth.external.google]
enabled = true
client_id = ""
secret = ""

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[edge_runtime]
enabled = true
