CREATE TABLE daily_checkins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  day_score NUMERIC,
  habits_completed INTEGER,
  habits_total INTEGER,
  calories_logged NUMERIC,
  protein_logged NUMERIC,
  workouts_completed INTEGER,
  sleep_hours NUMERIC,
  focus_hours NUMERIC,
  revenue_logged NUMERIC,
  water_oz NUMERIC,
  mood_average NUMERIC,
  ai_morning_briefing TEXT,
  ai_evening_reflection TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, date)
);

CREATE TABLE weekly_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  weight_change NUMERIC,
  workouts_completed INTEGER,
  workouts_target INTEGER,
  avg_calories NUMERIC,
  avg_protein NUMERIC,
  avg_sleep_hours NUMERIC,
  avg_mood NUMERIC,
  avg_readiness NUMERIC,
  habits_completion_rate NUMERIC,
  focus_hours_total NUMERIC,
  revenue_this_week NUMERIC,
  cumulative_revenue NUMERIC,
  new_customers INTEGER,
  prs_this_week INTEGER,
  top_wins TEXT[],
  areas_to_improve TEXT[],
  next_week_goals TEXT[],
  ai_weekly_summary TEXT,
  fitness_grade TEXT,
  nutrition_grade TEXT,
  business_grade TEXT,
  habits_grade TEXT,
  sleep_grade TEXT,
  overall_grade TEXT,
  body_business_correlations JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, week_start)
);

CREATE TABLE vision_board_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  title TEXT,
  category TEXT CHECK (category IN ('body','business','lifestyle','relationship','material','travel','personal')),
  linked_goal_id UUID REFERENCES goals(id),
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);
